# Generated by Django 2.1.3 on 2019-11-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='Event_Title',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='Organised_By',
        ),
    ]
